tasks:
  - name: Hasura
    init: |
      cd backend/hasura
      docker-compose pull
    command: |
      cd backend/hasura
      docker-compose up -d
  - name: Frontend
    init: |
      cd frontend/
      npm install
    command: |
      cd frontend/
      npm start

vscode:
  extensions:
    - editorconfig.editorconfig
    - ms-python.python
    - esbenp.prettier-vscode

ports:
  - port: 8124
    onOpen: notify
  - port: 3000
    onOpen: open-browser
